#---------------------------------------------------------------------

# This file was generated by wxImage Embedding Tool

from wx.lib.embeddedimage import PyEmbeddedImage

image_index = {}
image_catalog = {}
#---------------------------------------------------------------------

image_catalog["multimeter_png"] = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABHNCSVQIC"
    "AgIfAhkiAAAAUpJREFUaIHtml0OgjAMgDumdzDchMv54OW4CfEOBvEJs5"
    "Cutlv3U8P3SJewb2tXBJ0bPFhmaD2BXE6B1lyo4PZet1oToXCDd7EYKQA"
    "A8Ho+dGcj5Hq7k/H/TqGQXyuhDXfn2QIAAPOyJk1GyjTye5NIgHOzUBKL"
    "UeNTUKmBeVmjE8Fi1Hgp5ovYvIC4BsIc3tOAKjosdrw2jf5bH9LUEgtgN"
    "6BEsBhHnIv5FOpCIDV9ABT6AEA8p7FY7FrqsZotQNUEFdNCJKBRdNqwBV"
    "o/VscQ7UCtJ1LJYqn0AU2kadrFMZqDyjEqBevKqTTZAc00rC4wjT6562J"
    "UTaHjxDUkqu2A5qqHFN+BvWBLHb9FBUqtekiSgKTZSMZWe5yu9X6Ig/lO"
    "fAq05hRojXmBrDdzPSAS6PF3sfkUMi/gqL8aWPjMSgpYwHwKnQKt+QB52"
    "IBgteZUVAAAAABJRU5ErkJggg=="
   )

image_index[0] = "multimeter_png"

#---------------------------------------------------------------------

image_catalog["psu_png"] = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABHNCSVQIC"
    "AgIfAhkiAAAAYZJREFUaIHtmDFuwkAQRf+acIOI0gonoIiRUlHDEZCPkj"
    "pHsXKEUFNFCik4gaMtUW6AsFPF2QR7vGObHTbaV5md0TKf/WMPVioawWc"
    "i6QL6EgRIc0MFy+JUuiqEQkUj1RQjBQCA1vmw1TCJ4ykZ/98WMmn7JYbG"
    "9uStBQDAYvHQqRgu2+2rdS5LQB2b4/7X5+V4Rsao/C4M0gPL8ayxkLoYl"
    "c/F+yb2XkDvHgDOvd4W+7u2Oe6r/uBaK/SANFchoKt9gAv1gFmMTQ8A3Z"
    "8HvQXUffH3GhUbCpYAziPeFdYCpMfqJlgnQE2kk8ktdru31qlV6xxJMsf"
    "h8Enm2MLugabNk2QO4EcIlUPtwx3br+I22gfvBbAtZNrg0jk2KOrNXFmc"
    "Sum7TxxPybcS3lsoCJAmCJAmCJAmCJBmkL+UNtRNmVrnKNb3Z+vR87v1v"
    "s4EAECaptV1lmXV9ePdqrp++nhh7em9hbwX4NRCpm1MuLYxCeO0NK0n4L"
    "CWRqgTIAX4gPcWCgKk+QLxZni7L2b6WQAAAABJRU5ErkJggg=="
   )

image_index[1] = "psu_png"

#---------------------------------------------------------------------

image_catalog["ok_png"] = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABHNCSVQIC"
    "AgIfAhkiAAAAUNJREFUaIHtmkEOgjAQRV/RK7g18QLcxlN6Gy9gwpYzKK"
    "5MCJHCdKadNuFvK3Hem0HaYAjdiZbTeRegzQHgnXNscfq8p1KFxBK6U1h"
    "biwIADMPLthphrtdbdL35EToALNOPd/rxLrqmGoB54RKIKgCk1uepAmCZ"
    "5+Wx+7PuABr7UAHAMhL74AygtQ+VdUBqHxwBLOxDRR1IsQ9OAFb2wQHgX"
    "/Gp9qGCEdIUD4UBLEfnF9cOaO1DQYAc9sGxAxb2IQEg5dCRyz4IAVIOHd"
    "Y/m8uoRijFrGXxIAT49+UxiJyj84u4A1KIrWu1SRqhPRAl7IPiHpB2Iod"
    "9UN7EaxCl7IPBg2yP2Vz2wehJnLPArZhtJdYgcsOZ7oU8OmG+mZtDlADa"
    "fMGRkpKdcD9SanMAeKd5gBD7q0ELr1mjAC2k+RE6ALzzBcHsWuTPimOXA"
    "AAAAElFTkSuQmCC"
   )

image_index[2] = "ok_png"

#---------------------------------------------------------------------

image_catalog["cancel_png"] = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABHNCSVQIC"
    "AgIfAhkiAAAAU5JREFUaIHtmcENgzAQBNeQIvJCShG0QbFpI0VE4kUT4H"
    "x5wHH27WFQvF+LY0ec7cUOoWlxZzWlDVhVAUrrIQ3GZY5nGZEUmjbsjYk"
    "AADCOX66bRHXdSxy/fQtVgNKqAKWVBDANPaahdzGSW1sNsC7OhrDUzm4h"
    "FoS1jhrg+f7QX771/NZ7JCV9ASYEwzyQ0UIMCJZ5IHMOWCCY5gHDJM6BY"
    "JsHjBtZCoSHeYCwE2sgvMwDpCghQXiaB4hZSNtOTPMAOcwdmWObBxzS6J"
    "5JD/PAiXHaK8XSASSjHhBUAI1BNgQNYG/F8Uixa1EAjpZLTwgzgHat94I"
    "wAaRuVB4Q1F9KzVrPhsgCsEYEJkQyACvfsCCSz4U0RrRiQNB/aM6ukX0q"
    "wQxnlrpBuqWMyxyvcMEh3dD81+HuFVUBSutwEp/oZVfSJBYB7qDbt1AFK"
    "K0fYD2cJd8ouioAAAAASUVORK5CYII="
   )

image_index[3] = "cancel_png"

#---------------------------------------------------------------------

def GetData(name):
    return image_catalog[name].GetData()

def GetImage(name):
    return image_catalog[name].GetImage()

def GetBitmap(name):
    return image_catalog[name].GetBitmap()

def GetIcon(name):
    return image_catalog[name].GetIcon()

